# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "ansible-server"
  config.vm.box_check_update = false
  config.vm.define "ansible-server"
  config.vm.boot_timeout = 600
end

